Относительные ссылки с главной + стилистические уточнения по гайду API
best-doctor/guides pull request #26
Opened 2020-07-03 15:43 UTC by pavel64-sutyrin

2020-07-13 08:56 UTC, sutyrin commented on guides/api_guide.md
> -POST /patients/me HTTP/1.1
Вряд ли можно создать себя? ;)

2020-07-14 10:22 UTC, sergey-jerzy commented on guides/api_guide.md
> +В разделе `meta` может присутствовать поле `total`, обозначающие общее количество элементов в наборе, и поле `pages`,
У нас нет поля pages, только total. Общее количество страниц присутствует в last_url, если необходима последняя страница.

2020-07-14 10:22 UTC, sergey-jerzy commented on guides/api_guide.md
> +Параметр format сейчас json, вряд ли он станет xml когда-нибудь. yml возможен.
Лучше убрать упоминание yml и xml вообще, если какие-то форматы появятся, то мы дополним этот раздел.

2020-07-14 10:40 UTC, sergey-jerzy requested changes
Исправь, пожалуйста, замечания, которые в комментах были.

2020-07-15 09:21 UTC, sutyrin commented on guides/api_guide.md
> +В разделе `meta` может присутствовать поле `total`, обозначающие общее количество элементов в наборе, и поле `pages`,
1. Explicit is better, than implicit? 
2. Для относительной паджинации этот метод неприменим, стало быть, их будет два разных?
3. Алсо, известно [высказывание](https://www.facebook.com/melevir/posts/3638958739511939) @Melevir : «Кроме этого мы начали глобальную работу по переписыванию нашего API и первым делом описали то, **куда мы хотим прийти**, это превратилось в гайд по API.», т.е. здесь должен быть описан в первую очередь (обоснованно) желаемый статус и устройство API?

2020-07-15 09:24 UTC, sergey-jerzy commented on guides/api_guide.md
> +В разделе `meta` может присутствовать поле `total`, обозначающие общее количество элементов в наборе, и поле `pages`,
Относительная паджинация для больших коллекций на after-before описана далее. LimitOffset мапится 1-в-1 в PagePerPage. Получить значение pages можно из текущих total и per_page.

2020-07-15 09:55 UTC, sutyrin commented on guides/api_guide.md
> +В разделе `meta` может присутствовать поле `total`, обозначающие общее количество элементов в наборе, и поле `pages`,
Так [вот же он](https://github.com/best-doctor/guides/blame/baed18134fedfff26ece7df9103988d3ce5b8584/guides/api_guide.md#L211), `pages`.

Ну и раз он так легко мапится, так может, реализовать эти простейшие формулы на стороне сервера и возвращать гарантированные сервером значения? Есть риск, что разработчик клиента, пытаясь реализовать эти переводные формулы у себя на клиенте, что-то напортачит в стиле off-by-one. Помножить на количество разработчиков клиентов.

2020-07-15 10:15 UTC, sergey-jerzy commented on guides/api_guide.md
> +В разделе `meta` может присутствовать поле `total`, обозначающие общее количество элементов в наборе, и поле `pages`,
Да, дух HATEOAS дает нам ссылки на пару соседних страниц. При количестве страницы больше 10 ты даже паджинатор особо не отрисуешь кроме пары соседних страниц, так что шаблонизация с номером страницы тут не особо важна и критична.

Сейчас параметр pages отсутствует, я его уберу из примеров, если в таком виде PR зальем. Кроме того, параметр total тоже может отсутствовать, если для паджинатора отключено использование count на коллекции.

2020-07-15 10:20 UTC, sutyrin commented on guides/api_guide.md
> +В разделе `meta` может присутствовать поле `total`, обозначающие общее количество элементов в наборе, и поле `pages`,
OK

2020-07-16 09:42 UTC, sutyrin commented on guides/api_guide.md
> +В разделе `meta` может присутствовать поле `total`, обозначающие общее количество элементов в наборе, и поле `pages`,
Так зальём, и затем вы удалите примеры и упоминания `pages`? Или как?)

2020-07-16 10:00 UTC, sergey-jerzy approved these changes

2020-07-17 07:02 UTC, merged

2020-07-17 07:03 UTC, Melevir commented
@sutyrin спасибо! :)