Стайлгайд для тестов
best-doctor/guides pull request #5
Opened 2019-07-15 11:00 UTC by vergeev

![YXhT6fA](https://user-images.githubusercontent.com/13587415/61211634-bf259900-a708-11e9-92bd-b3423ac94012.gif)

Хочу выслушать предложения по его улучшению до ближайшего бекенд-синка.

2019-07-15 11:23 UTC, Melevir requested changes

2019-07-15 11:23 UTC, Melevir commented on guides/python_test_styleguide.md
> +## `selenium` vs `client.get`
Ты, наверное, имел в виду `django.test.Client`

2019-07-15 11:23 UTC, Melevir commented on guides/python_test_styleguide.md
> +Мы используем `client.get` за его легковесность.
Я бы сказал, что используем клиент для не-юнитов, если это возможно. То, что что-то там используют QA к этому не имеет отношения, кажется.

2019-07-15 11:23 UTC, Melevir commented on guides/python_test_styleguide.md
> +Чтобы избегать дубликации кода при написании тестов, мы их параметризируем с помощью `pytest.parameterize`. Благодаря этому `success_case`-тестов редко бывает больше одного.
Про `ids` замолвить бы словечко. Кажется, что в некоторых случаях ids надо форсить.

2019-07-15 11:23 UTC, Melevir commented on guides/python_test_styleguide.md
> +Мы используем `pytest.xfails`, чтобы избежать ломающегося билда. Мы используем `pytest.raises`, чтобы показать, что тест проходит только в случае, если поднимается исключение.
Хорошо бы перечислить, в каких случаях мы используем эти штуки и зачем. Ты же не хочешь сказать, что мы фейлим тесты когда они сломаны чтобы билд не ломать.

2019-07-15 11:23 UTC, Melevir commented on guides/python_test_styleguide.md
> +Это нужно делать в тесте.
Кажется, это должна уметь делать фабрика. Непонятно, зачем тест захламлять подготовкой данных.

2019-07-15 11:23 UTC, Melevir commented on guides/python_test_styleguide.md
> +## Шаблон теста
Во-первых, кажется, что это шаблон именно юнит-теста. 
Во-вторых, хорошо бы замолвить словечко за AAA (https://medium.com/@pjbgf/title-testing-code-ocd-and-the-aaa-pattern-df453975ab80).

2019-07-15 11:23 UTC, Melevir commented on guides/python_test_styleguide.md
> +Эти гайдлайны являются _добровольными_. Если какое-то правило не приживётся, от него можно просто избавиться в следующей версии документа.
Нет, с этим категорически не согласен, правила одни для всех и они должны быть обязательны. Часть корабля – часть команды.

2019-07-15 11:23 UTC, Melevir commented on guides/python_test_styleguide.md
> +Эти гайдлайны являются _добровольными_. Если какое-то правило не приживётся, от него можно просто избавиться в следующей версии документа.
... но это не отменяет того, что гайд дорабатываем и говно выпиливаем, а крутоту добавляем.

2019-07-15 11:23 UTC, Melevir commented on guides/python_test_styleguide.md
> +Этот документ дополняет [Python Styleguide](https://github.com/best-doctor/guides/blob/master/guides/python_styleguide.md). При конфликте правил этот документ имеет преимущество.
Кажется, что конфликтов быть не должно, гайды про разное. Ещё мне почему-то кажется, что этот блок лишний.

2019-07-15 11:23 UTC, Melevir commented on guides/python_test_styleguide.md
> +2. Что функции и методы, составляющие фичу, работают как надо
Скорее тут речь про то, что конкретная функция/метод работает как надо. Единственное число.

2019-07-15 11:29 UTC, vergeev commented on guides/python_test_styleguide.md
> +Этот документ дополняет [Python Styleguide](https://github.com/best-doctor/guides/blob/master/guides/python_styleguide.md). При конфликте правил этот документ имеет преимущество.
Да, я плохо показал его нужность. Смысл был в том, чтобы сказать: "внутри тестов мы всё ещё соблюдаем этот стайлгайд". Перепишу.

2019-07-15 11:29 UTC, vergeev commented on guides/python_test_styleguide.md
> +Эти гайдлайны являются _добровольными_. Если какое-то правило не приживётся, от него можно просто избавиться в следующей версии документа.
Понял, перепишу механизм доработки гайда.

2019-07-15 11:30 UTC, vergeev commented on guides/python_test_styleguide.md
> +Это нужно делать в тесте.
То есть на фабрике должен быть такой метод?

2019-07-15 11:32 UTC, Melevir commented on guides/python_test_styleguide.md
> +Это нужно делать в тесте.
Например. Иначе же не драй, всё такое.

2019-07-15 14:32 UTC, vergeev commented on guides/python_test_styleguide.md
> +2. Что функции и методы, составляющие фичу, работают как надо
Фича может состоять из нескольких функций и методов. Предполагается, что они будут тестироваться как отдельно, так и все вместе (на уровне "фича работает").

2019-07-16 09:13 UTC, kazauwa reviewed
Я бы ещё добавил, пунктик про моки и почему вместо них надо использовать фейки.

Моки проверяют только то, что какой-то аттрибут вызвали. Если это callable, то ещё и параметры с которыми он вызывается. Это ненадёжно, потому что тест минует часть бизнес-логики, которая может влиять на выполнение тестируемой фичи в бою. Плюс, если приходится мокать - значит наш код слишком связан и это проблема, которую надо решать. Ну и наконец, не стоит мешать unittest и pytest

2019-07-16 09:13 UTC, kazauwa commented on guides/python_test_styleguide.md
> +## `selenium` vs `django.test.Client`
Необходимости в селениуме как не было, так скорее всего и не появится. Мне кажется, он тут вообще не нужен

2019-07-16 09:13 UTC, kazauwa commented on guides/python_test_styleguide.md
> +Новые фабрики добавляются в `bestdoctor/factories.py` и регистрируются в `bestdoctor/tests/conftest.py`. Далее они доступны тестам в качестве параметров.
Мне кажется, надо фабрики бить по файлам по аналогии с тестами и с моделями. В `factory.py` уже дикий бардак

2019-07-16 09:13 UTC, kazauwa commented on guides/python_test_styleguide.md
> +Такие вещи лучше реализовывать в виде метода на фабрике. Это позволит избежать дубликации усилий.
Как ты предлагаешь реализовывать n фабрик? Через классовый метод? Добавь пример как делать правильно.

2019-07-16 09:30 UTC, Melevir commented on guides/python_test_styleguide.md
> +Такие вещи лучше реализовывать в виде метода на фабрике. Это позволит избежать дубликации усилий.
Давайте потом накинем примеров и распишем подробнее. Не хочется пидорасить этот пр, хочется сделать 10 новых с доработками по горячим следам.

2019-07-16 11:15 UTC, vergeev commented on guides/python_test_styleguide.md
> +Такие вещи лучше реализовывать в виде метода на фабрике. Это позволит избежать дубликации усилий.
https://github.com/best-doctor/guides/issues/9

2019-07-16 12:01 UTC, merged